spring:
    datasource:
        password: ${DATABASE_PASSWORD:testpw}
        url: ${DATABASE_URL:jdbc:mysql://localhost:3306/test}
        username: ${DATABASE_USERNAME:test}
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    thymeleaf:
        cache: false